export const TYPES = {
    INCREMENT: "INCREMENT",
    DECREMENT: "DECREMENT",
    INCREMENT_5: "INCREMENT_5",
    DECREMENT_5: "DECREMENT_5",
    DIVIDE: "DIVIDE",
    MULTIPLICATE: "MULTIPLICATE",
    RESET: "RESET",
}


